title: Apollo Engine
subtitle: Using Engine
versions:
  - '1'
sidebar_categories:
  null:
    - index
  Features:
    - features/schema-explorer
    - features/schema-history
    - features/performance
    - features/query-tracing
    - features/error-tracking
    - features/alerts
  Engine Proxy:
    - 1.0-migration

github_repo: apollographql/engine-docs

apis:
  segment: awKBAQ3eIgXIChDoy119j6ab4R4tqcXr

nav_links:
  'Engine':
    url: http://engine.apollographql.com

url: https://www.apollographql.com/docs/engine/
root: /docs/engine/

public_dir: public/docs/engine
